name: Build and deploy ASP.Net Core app to Azure Web App - Reactivities-coursework

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Checkout main repository
      - uses: actions/checkout@v4

      # Checkout React app
      - name: Checkout React app
        uses: actions/checkout@v4
        with:
          repository: saikiran37130204/ReactivitiesClientSide
          path: reactivities-client
          token: ${{ secrets.GITHUB_TOKEN }}

      # Node.js setup
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'reactivities-client/client-app/package-lock.json'

      # Build React app with modified Vite output
      - name: Build React app
        working-directory: reactivities-client/client-app
        run: |
          # Temporarily modify Vite config to output to dist folder first
          echo "Modifying Vite config for CI build..."
          sed -i 's|outDir: .*|outDir: "../dist",|' vite.config.ts
          
          npm ci --no-audit
          npm run build
          
          echo "Build output:"
          ls -la ../dist/
        shell: bash

      # .NET setup
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      # Copy from temporary dist folder to wwwroot
      - name: Copy React build
        run: |
          mkdir -p API/wwwroot
          cp -r reactivities-client/dist/* API/wwwroot/
          
          echo "Copied files:"
          ls -la API/wwwroot/
        shell: bash

      # Restore original Vite config
      - name: Restore Vite config
        working-directory: reactivities-client/client-app
        run: |
          git checkout -- vite.config.ts
        shell: bash

      # .NET build and publish
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3914583C92DD4E72A608EAB40AAEF26D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA974CF49E4E474F89576C5988ED3FF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4735E5C4CB3A4B68906DA55A6D7CCD3E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Reactivities-coursework"
          slot-name: "Production"
          package: .