name: Build and deploy ASP.Net Core app to Azure Web App - Reactivities-coursework

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      # Checkout the .NET API repository
      - uses: actions/checkout@v4

      # Checkout the React app repository into a subdirectory
      - name: Checkout React app
        uses: actions/checkout@v4
        with:
          repository: saikiran37130204/ReactivitiesClientSide
          path: client-app
          token: ${{ secrets.GITHUB_TOKEN }} # Needed for private repos

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install deps and build react app
        run: |
          cd client-app
          npm install
          npm run build
        working-directory: client-app

      - name: Verify React build output
        working-directory: client-app
        run: |
          echo "Build directory contents:"
          ls -la dist/
        shell: bash

      - name: Copy React build to API wwwroot
        run: |
          mkdir -p API/wwwroot
          cp -r client-app/dist/* API/wwwroot/

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3914583C92DD4E72A608EAB40AAEF26D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA974CF49E4E474F89576C5988ED3FF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4735E5C4CB3A4B68906DA55A6D7CCD3E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Reactivities-coursework"
          slot-name: "Production"
          package: .
