name: Build and deploy ASP.Net Core app to Azure Web App - Reactivities-coursework

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Checkout React app
        uses: actions/checkout@v4
        with:
          repository: saikiran37130204/ReactivitiesClientSide
          path: reactivities-client
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "reactivities-client/client-app/package-lock.json"

      - name: Build React app
        working-directory: reactivities-client/client-app
        run: |
          echo "Modifying Vite config..."
          sed -i 's|outDir: .*|outDir: "../dist",|' vite.config.ts
          npm ci --no-audit
          npm run build
          echo "Build output:"
          ls -la ../dist/
          ls -la ../dist/assets/
          if [ ! -f ../dist/index.html ]; then
            echo "Error: React build failed - index.html not found"
            exit 1
          fi
          if [ ! -f ../dist/assets/index-*.js ]; then
            echo "Error: React build failed - main JS file not found"
            exit 1
          fi
        shell: bash

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Copy React build
        run: |
          mkdir -p API/wwwroot
          rm -rf reactivities-client/dist/assets || true
          rm -rf reactivities-client/dist/vite.svg || true
          cp -r reactivities-client/dist/* API/wwwroot/
          echo "Copied files:"
          ls -la API/wwwroot/
          ls -la API/wwwroot/assets/
          if [ ! -f API/wwwroot/index.html ]; then
            echo "Error: Copy failed - index.html not found"
            exit 1
          fi
          if [ ! -d API/wwwroot/assets ]; then
            echo "Error: Copy failed - assets folder not found"
            exit 1
          fi
        shell: bash

      - name: Restore Vite config
        working-directory: reactivities-client/client-app
        run: |
          git checkout -- vite.config.ts
        shell: bash

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish API/API.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-restore
          echo "Published files:"
          dir "${{env.DOTNET_ROOT}}\myapp"
          dir "${{env.DOTNET_ROOT}}\myapp\wwwroot"
          if not exist "${{env.DOTNET_ROOT}}\myapp\wwwroot\index.html" (
            echo "Error: Publish failed - index.html not found"
            exit /b 1
          )
        shell: cmd

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3914583C92DD4E72A608EAB40AAEF26D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AA974CF49E4E474F89576C5988ED3FF1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4735E5C4CB3A4B68906DA55A6D7CCD3E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Reactivities-coursework"
          slot-name: "Production"
          package: .
